sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
services:
  - docker
script:
  - npm run lint
  - npm run test
after_success:
  - sh ./scripts/build.sh

