sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
services:
  - docker
script:
  - npm run lint
  - npm run test
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    echo "building and publishing docker image";
    DOCKER_IMAGE=$(scripts/build.sh);
    docker push "$DOCKER_IMAGE";
    fi

