sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
services:
  - docker
script:
  - npm run lint
  - npm run test
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      echo "building and publishing docker image";
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      DOCKER_TAG=$(./tag.sh)
      echo "building image ${DOCKER_TAG}"
      ./build.sh "$DOCKER_TAG"
      docker push leankit/cowpoke:"$DOCKER_TAG"
    fi

